/**
 * student-data.js
 * ข้อมูลนักศึกษาสำหรับ Portfolio Dashboard
 * แก้ไขข้อมูลในไฟล์นี้เพื่อปรับแต่ง Portfolio ของคุณ
 */

const studentData = {
  // ข้อมูลส่วนตัว
  personal: {
    nameTH: "นายธนกร วงศ์สุวรรณ",
    nameEN: "Thanakorn Wongsuwan",
    studentId: "6401234567",
    faculty: "คณะวิทยาศาสตร์และเทคโนโลยี",
    major: "วิทยาการคอมพิวเตอร์",
    university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
    year: "ชั้นปีที่ 4",
    email: "thanakorn.w@mail.kmutt.ac.th",
    phone: "098-765-4321",
    github: "github.com/thanakorn-w",
    linkedin: "linkedin.com/in/thanakorn-w",
    gpaOverall: "3.65",
    profileInitials: "ธว",
  },

  // ผลการเรียนรายเทอม
  academicResults: {
    semesters: [
      {
        name: "เทอม 1/64",
        gpa: 3.5,
        credits: 18,
        subjects: [
          { code: "CS101", name: "Introduction to Programming", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "MATH101", name: "Calculus I", credits: 3, grade: "B+", gradePoint: 3.5 },
          { code: "PHYS101", name: "Physics I", credits: 3, grade: "B+", gradePoint: 3.5 },
          { code: "ENG101", name: "English I", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS102", name: "Discrete Mathematics", credits: 3, grade: "A-", gradePoint: 3.67 },
          { code: "GE101", name: "Civic Education", credits: 3, grade: "A", gradePoint: 4.0 },
        ],
      },
      {
        name: "เทอม 2/64",
        gpa: 3.6,
        credits: 18,
        subjects: [
          { code: "CS201", name: "Data Structures", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "MATH102", name: "Calculus II", credits: 3, grade: "B+", gradePoint: 3.5 },
          { code: "CS202", name: "Digital Logic", credits: 3, grade: "A-", gradePoint: 3.67 },
          { code: "ENG102", name: "English II", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS203", name: "Object-Oriented Programming", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "GE102", name: "Thai Studies", credits: 3, grade: "A-", gradePoint: 3.67 },
        ],
      },
      {
        name: "เทอม 1/65",
        gpa: 3.7,
        credits: 18,
        subjects: [
          { code: "CS301", name: "Algorithms", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS302", name: "Database Systems", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS303", name: "Computer Networks", credits: 3, grade: "B+", gradePoint: 3.5 },
          { code: "CS304", name: "Operating Systems", credits: 3, grade: "A-", gradePoint: 3.67 },
          { code: "MATH201", name: "Linear Algebra", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "ENG201", name: "Technical Writing", credits: 3, grade: "A", gradePoint: 4.0 },
        ],
      },
      {
        name: "เทอม 2/65",
        gpa: 3.75,
        credits: 18,
        subjects: [
          { code: "CS401", name: "Software Engineering", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS402", name: "Web Development", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS403", name: "Machine Learning", credits: 3, grade: "A-", gradePoint: 3.67 },
          { code: "CS404", name: "Computer Security", credits: 3, grade: "B+", gradePoint: 3.5 },
          { code: "CS405", name: "Human-Computer Interaction", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS406", name: "Mobile Application Development", credits: 3, grade: "A", gradePoint: 4.0 },
        ],
      },
      {
        name: "เทอม 1/66",
        gpa: 3.8,
        credits: 18,
        subjects: [
          { code: "CS501", name: "Deep Learning", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS502", name: "Cloud Computing", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS503", name: "DevOps Engineering", credits: 3, grade: "A-", gradePoint: 3.67 },
          { code: "CS504", name: "Data Engineering", credits: 3, grade: "A", gradePoint: 4.0 },
          { code: "CS505", name: "Blockchain Technology", credits: 3, grade: "B+", gradePoint: 3.5 },
          { code: "CS506", name: "Research Methodology", credits: 3, grade: "A", gradePoint: 4.0 },
        ],
      },
      {
        name: "เทอม 2/66",
        gpa: 3.65,
        credits: 15,
        subjects: [
          { code: "CS601", name: "Senior Project I", credits: 6, grade: "A", gradePoint: 4.0 },
          { code: "CS602", name: "Internship", credits: 6, grade: "A", gradePoint: 4.0 },
          { code: "CS603", name: "Ethics in Computing", credits: 3, grade: "A-", gradePoint: 3.67 },
        ],
      },
    ],
  },

  // วิชาที่เรียนได้ดี
  excellentSubjects: [
    {
      code: "CS301",
      name: "Algorithms",
      nameEN: "Algorithms & Data Structures",
      grade: "A",
      gpa: 4.0,
      semester: "เทอม 1/65",
      description: "ออกแบบและวิเคราะห์อัลกอริทึมที่มีประสิทธิภาพสูง",
      icon: "🧮",
    },
    {
      code: "CS402",
      name: "Web Development",
      nameEN: "Full-Stack Web Development",
      grade: "A",
      gpa: 4.0,
      semester: "เทอม 2/65",
      description: "พัฒนาเว็บแอปพลิเคชันด้วย React, Node.js และ PostgreSQL",
      icon: "🌐",
    },
    {
      code: "CS403",
      name: "Machine Learning",
      nameEN: "Machine Learning & AI",
      grade: "A-",
      gpa: 3.67,
      semester: "เทอม 2/65",
      description: "สร้างโมเดล ML ด้วย Python, TensorFlow และ scikit-learn",
      icon: "🤖",
    },
    {
      code: "CS302",
      name: "Database Systems",
      nameEN: "Database Design & Management",
      grade: "A",
      gpa: 4.0,
      semester: "เทอม 1/65",
      description: "ออกแบบฐานข้อมูลเชิงสัมพันธ์และ NoSQL",
      icon: "🗄️",
    },
    {
      code: "CS501",
      name: "Deep Learning",
      nameEN: "Deep Learning & Neural Networks",
      grade: "A",
      gpa: 4.0,
      semester: "เทอม 1/66",
      description: "ออกแบบ Neural Networks ด้วย PyTorch และ TensorFlow",
      icon: "🧠",
    },
    {
      code: "CS502",
      name: "Cloud Computing",
      nameEN: "Cloud Architecture & DevOps",
      grade: "A",
      gpa: 4.0,
      semester: "เทอม 1/66",
      description: "บริหารจัดการ Cloud Infrastructure บน AWS และ GCP",
      icon: "☁️",
    },
  ],

  // ทักษะ
  skills: {
    technical: [
      { name: "Python", level: 90, category: "Programming" },
      { name: "JavaScript / TypeScript", level: 85, category: "Programming" },
      { name: "React.js", level: 80, category: "Framework" },
      { name: "Node.js", level: 78, category: "Framework" },
      { name: "Machine Learning", level: 75, category: "AI/ML" },
      { name: "SQL / PostgreSQL", level: 82, category: "Database" },
      { name: "Docker / Kubernetes", level: 70, category: "DevOps" },
      { name: "AWS Cloud", level: 68, category: "Cloud" },
      { name: "Git / GitHub", level: 88, category: "Tools" },
      { name: "TensorFlow / PyTorch", level: 72, category: "AI/ML" },
    ],
    soft: [
      { name: "การแก้ปัญหา (Problem Solving)", level: 92 },
      { name: "การทำงานเป็นทีม (Teamwork)", level: 88 },
      { name: "การสื่อสาร (Communication)", level: 82 },
      { name: "ความคิดสร้างสรรค์ (Creativity)", level: 85 },
      { name: "การบริหารเวลา (Time Management)", level: 80 },
      { name: "ความเป็นผู้นำ (Leadership)", level: 75 },
    ],
  },

  // อาชีพที่เหมาะสม
  careers: [
    {
      title: "Full-Stack Developer",
      titleTH: "นักพัฒนาซอฟต์แวร์",
      match: 95,
      salary: "40,000 - 80,000 บาท/เดือน",
      description: "พัฒนาเว็บแอปพลิเคชันทั้ง Frontend และ Backend",
      skills: ["React", "Node.js", "PostgreSQL", "Docker"],
      growth: "สูงมาก",
      icon: "💻",
      color: "#4F46E5",
    },
    {
      title: "Machine Learning Engineer",
      titleTH: "วิศวกร Machine Learning",
      match: 88,
      salary: "50,000 - 100,000 บาท/เดือน",
      description: "ออกแบบและพัฒนาโมเดล AI สำหรับงานจริง",
      skills: ["Python", "TensorFlow", "PyTorch", "MLOps"],
      growth: "สูงมาก",
      icon: "🤖",
      color: "#7C3AED",
    },
    {
      title: "Data Engineer",
      titleTH: "วิศวกรข้อมูล",
      match: 82,
      salary: "45,000 - 90,000 บาท/เดือน",
      description: "สร้างและบริหาร Data Pipeline สำหรับองค์กร",
      skills: ["Python", "SQL", "Spark", "Airflow"],
      growth: "สูง",
      icon: "📊",
      color: "#0891B2",
    },
    {
      title: "DevOps / Cloud Engineer",
      titleTH: "วิศวกร DevOps / Cloud",
      match: 78,
      salary: "45,000 - 85,000 บาท/เดือน",
      description: "บริหาร Cloud Infrastructure และ CI/CD Pipeline",
      skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
      growth: "สูง",
      icon: "☁️",
      color: "#059669",
    },
    {
      title: "AI Research Engineer",
      titleTH: "นักวิจัย AI",
      match: 72,
      salary: "55,000 - 120,000 บาท/เดือน",
      description: "วิจัยและพัฒนาเทคโนโลยี AI ใหม่ๆ",
      skills: ["Deep Learning", "Research", "Python", "Math"],
      growth: "สูงมาก",
      icon: "🔬",
      color: "#DC2626",
    },
    {
      title: "Cybersecurity Analyst",
      titleTH: "นักวิเคราะห์ความมั่นคงปลอดภัย",
      match: 65,
      salary: "40,000 - 80,000 บาท/เดือน",
      description: "ป้องกันและวิเคราะห์ภัยคุกคามทางไซเบอร์",
      skills: ["Security", "Networking", "Ethical Hacking"],
      growth: "สูง",
      icon: "🔒",
      color: "#B45309",
    },
  ],

  // ประสบการณ์
  experiences: [
    {
      type: "internship",
      title: "Software Engineer Intern",
      organization: "LINE Thailand",
      period: "มิ.ย. 2566 - ส.ค. 2566",
      duration: "3 เดือน",
      description:
        "พัฒนา Microservices ด้วย Go และ Node.js สำหรับระบบ LINE Shopping ดูแลระบบที่มีผู้ใช้งาน 5 ล้านคน",
      skills: ["Go", "Node.js", "Kubernetes", "MySQL"],
      achievement: "เพิ่มประสิทธิภาพระบบ 40%",
      icon: "💼",
      color: "#06B6D4",
    },
    {
      type: "project",
      title: "Senior Project: AI-Powered Learning Platform",
      organization: "KMUTT",
      period: "ม.ค. 2566 - ปัจจุบัน",
      duration: "12 เดือน",
      description:
        "ออกแบบและพัฒนาระบบ E-Learning ที่ใช้ AI แนะนำเนื้อหาการเรียนรู้แบบ Personalized ให้กับนักศึกษา",
      skills: ["React", "Python", "FastAPI", "Machine Learning", "PostgreSQL"],
      achievement: "ได้รับรางวัล Best Project ของภาควิชา",
      icon: "🎓",
      color: "#8B5CF6",
    },
    {
      type: "competition",
      title: "ชนะเลิศ Thailand AI Hackathon 2023",
      organization: "NECTEC",
      period: "ต.ค. 2566",
      duration: "48 ชั่วโมง",
      description:
        "พัฒนาระบบ AI สำหรับวินิจฉัยโรคจากภาพ X-Ray ด้วย Deep Learning ความแม่นยำ 94.5%",
      skills: ["Python", "TensorFlow", "Computer Vision", "FastAPI"],
      achievement: "รางวัลชนะเลิศ ได้รับเงินรางวัล 100,000 บาท",
      icon: "🏆",
      color: "#F59E0B",
    },
    {
      type: "activity",
      title: "ประธานชมรม Computer Science Club",
      organization: "KMUTT",
      period: "มิ.ย. 2565 - พ.ค. 2566",
      duration: "1 ปี",
      description:
        "บริหารชมรมที่มีสมาชิก 120 คน จัดกิจกรรม Workshop และ Hackathon ภายในมหาวิทยาลัย",
      skills: ["Leadership", "Event Management", "Public Speaking"],
      achievement: "จัดกิจกรรมสำเร็จ 15 ครั้ง มีผู้เข้าร่วมรวม 800+ คน",
      icon: "👥",
      color: "#10B981",
    },
    {
      type: "freelance",
      title: "Freelance Web Developer",
      organization: "Self-employed",
      period: "ม.ค. 2565 - ปัจจุบัน",
      duration: "2+ ปี",
      description: "รับพัฒนาเว็บแอปพลิเคชันให้ลูกค้า SME ไทย ทั้ง E-Commerce และ Business System",
      skills: ["React", "Next.js", "Node.js", "WordPress"],
      achievement: "ส่งมอบโปรเจกต์สำเร็จ 12 โปรเจกต์ รายได้ 300,000+ บาท",
      icon: "🚀",
      color: "#EF4444",
    },
    {
      type: "opensource",
      title: "Open Source Contributor",
      organization: "GitHub",
      period: "ม.ค. 2565 - ปัจจุบัน",
      duration: "2+ ปี",
      description: "มีส่วนร่วมใน Open Source Projects ด้าน AI/ML และ Web Development",
      skills: ["Python", "JavaScript", "Git", "Documentation"],
      achievement: "100+ GitHub Stars, ส่ง PR ที่ merge แล้ว 45+ รายการ",
      icon: "🌟",
      color: "#6366F1",
    },
  ],

  // บริษัทที่ match
  companies: [
    {
      name: "LINE Thailand",
      logo: "LINE",
      industry: "Technology / Social Media",
      match: 96,
      size: "Large (1,000+ คน)",
      location: "กรุงเทพฯ",
      salary: "50,000 - 90,000 บาท/เดือน",
      culture: ["Innovation", "Work-Life Balance", "Global Team"],
      whyMatch: [
        "ประสบการณ์ Internship ที่ LINE แล้ว",
        "ทักษะ Node.js ตรงกับ Tech Stack",
        "วัฒนธรรมองค์กรเน้น Engineering Excellence",
      ],
      openPositions: ["Backend Engineer", "Full-Stack Developer"],
      color: "#06C755",
      logoColor: "#06C755",
    },
    {
      name: "Agoda",
      logo: "AGD",
      industry: "Travel Technology",
      match: 92,
      size: "Large (3,000+ คน)",
      location: "กรุงเทพฯ",
      salary: "60,000 - 120,000 บาท/เดือน",
      culture: ["Data-Driven", "Fast-paced", "International"],
      whyMatch: [
        "ทักษะ Full-Stack ตรงกับ Job Requirements",
        "ความสามารถด้าน Machine Learning",
        "ประสบการณ์ Scale-up System",
      ],
      openPositions: ["Software Engineer", "ML Engineer"],
      color: "#FF5722",
      logoColor: "#FF5722",
    },
    {
      name: "SCB Tech X",
      logo: "SCB",
      industry: "FinTech",
      match: 87,
      size: "Medium (500-1,000 คน)",
      location: "กรุงเทพฯ",
      salary: "55,000 - 100,000 บาท/เดือน",
      culture: ["Digital Transformation", "Innovation", "Security"],
      whyMatch: [
        "ทักษะ Cybersecurity ตรงกับ FinTech",
        "ความสามารถด้าน Cloud Architecture",
        "GPA สูง ตรงตาม Requirement",
      ],
      openPositions: ["Cloud Engineer", "Security Engineer"],
      color: "#6C31A3",
      logoColor: "#6C31A3",
    },
    {
      name: "KBTG (Kasikorn)",
      logo: "KTB",
      industry: "FinTech / Banking",
      match: 84,
      size: "Medium (800+ คน)",
      location: "กรุงเทพฯ",
      salary: "50,000 - 90,000 บาท/เดือน",
      culture: ["Innovation", "Agile", "Thai Company"],
      whyMatch: [
        "ทักษะ Backend Development แข็งแกร่ง",
        "ประสบการณ์ Microservices Architecture",
        "ชื่นชอบ Culture แบบ Startup ในองค์กรใหญ่",
      ],
      openPositions: ["Software Engineer", "Data Engineer"],
      color: "#009933",
      logoColor: "#009933",
    },
    {
      name: "Bitkub",
      logo: "BKB",
      industry: "Cryptocurrency / Blockchain",
      match: 79,
      size: "Medium (400+ คน)",
      location: "กรุงเทพฯ",
      salary: "45,000 - 85,000 บาท/เดือน",
      culture: ["Startup", "Fast-growth", "Crypto-native"],
      whyMatch: [
        "ศึกษา Blockchain Technology มาแล้ว",
        "ทักษะ Backend ตรงกับ Requirements",
        "สนใจ Web3 และ DeFi",
      ],
      openPositions: ["Backend Engineer", "Blockchain Developer"],
      color: "#F0B90B",
      logoColor: "#F0B90B",
    },
    {
      name: "True Digital",
      logo: "TDG",
      industry: "Telecom / Digital Services",
      match: 75,
      size: "Large (2,000+ คน)",
      location: "กรุงเทพฯ",
      salary: "45,000 - 80,000 บาท/เดือน",
      culture: ["Digital Transformation", "Corporate", "Large Scale"],
      whyMatch: [
        "ทักษะ Cloud Computing ตรงกับ Infrastructure",
        "ประสบการณ์ DevOps มีประโยชน์",
        "Scale ที่ใหญ่มากเป็น Learning Opportunity",
      ],
      openPositions: ["DevOps Engineer", "Full-Stack Developer"],
      color: "#E60026",
      logoColor: "#E60026",
    },
  ],
};

// Export สำหรับใช้ใน module system
if (typeof module !== "undefined" && module.exports) {
  module.exports = studentData;
}
